import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XELARENA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="w-full border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-black">
          <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">

            {/* Left side — Home link */}
            <Link href="/" className="flex text-xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100" >
              <Image src="/favicon.ico"
                  alt="XELARENA logo"
                  width={28} 
                  height={28} 
                  className="rounded-sm" />

              <span className="text-xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">
                XELARENA
              </span>
            </Link>

            {/* alextodo??? Right side — PayPal Donate Button
            <form action="https://www.paypal.com/donate" method="post" target="_blank" >
              <input type="hidden" name="hosted_button_id" value="YOUR_BUTTON_ID" />
              <button type="submit" className="bg-[#003087] text-white px-4 py-2 rounded-md hover:bg-[#001f5c] transition" >
                Donate
              </button>
            </form>
            */}

          </div>
        </header>

        {children}
      <p>
        built by: 
        <a 
        href="https://www.linkedin.com/in/alexander-alexander-7861102b/"
        target="_blank"
        className=" text-[#F5E7C8] drop-shadow-[0_0_6px_rgba(245,231,200,0.6)] hover:text-[#E8D7A8] hover:drop-shadow-[0_0_12px_rgba(245,231,200,0.9)] transition-all blink bg-[#A5EEC8] px-1 rounded-md ml-1"
        >
        ALEXANDER</a>
      </p>
    </body>
    </html>
  );
}
