import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XELARENA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <p>
        built by: 
        <a 
        href="https://www.linkedin.com/in/alexander-alexander-7861102b/"
        target="_blank"
        className=" text-[#F5E7C8] drop-shadow-[0_0_6px_rgba(245,231,200,0.6)] hover:text-[#E8D7A8] hover:drop-shadow-[0_0_12px_rgba(245,231,200,0.9)] transition-all blink bg-[#A5EEC8] px-1 rounded-md ml-1"
        >
        ALEXANDER</a>
      </p>
    </body>
    </html>
  );
}
